# syntax=docker/dockerfile:1

FROM python:3.11.3-slim-bullseye

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y netcat default-libmysqlclient-dev
RUN rm -rf /var/lib/apt/lists/*

RUN mkdir /audit/
RUN mkdir /audit/script/
WORKDIR /audit/script/

COPY requirements.txt .
COPY config.ini .
COPY *.py .
COPY start-audit.sh .

RUN chmod u+x start-audit.sh

RUN pip install --upgrade pip \
    && pip install -r requirements.txt

ENTRYPOINT ["./start-audit.sh"]