services:
  
  database:
    build:
      dockerfile: Dockerfile_database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: SemgrepResults
    ports:
      - 3306:3306
    restart: always

  audit:
    build:
      dockerfile: Dockerfile_audit
    restart: always
    depends_on:
      - database